name: deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Run Tests
      run: npm run test-all
    - name: Deploy to GH Pages
      run: |
        git config --global user.email "${{ secrets.GITHUB_EMAIL }}"
        git config --global user.name "${{ secrets.GITHUB_NAME }}"
        git remote set-url origin ${{ secrets.GITHUB_URL }}
        npm run deploy
        echo "Deployed successfully"
